### PR TITLE
Code Updates for compatibility with QGIS 3.28 and because of changes in Nominatim JSON response

### PR DESCRIPTION
**Pull request by cxcandid**
Nominatim no longer shows "icon" fields in JSON responses. We therefore have to provide our own mapping. The template for this can be found here: https://github.com/osm-search/nominatim-ui/blob/master/src/components/MapIcon.svelte

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Thanks! Will test and try to release this week!

**Comment by rduivenvoorde** [comment]
@cxcandid I've commented out the map icon code for now sorry
It gave to many warnings in my Qt logs, and more important, it kept fetching the icons from the nominatim ui site.

I understand why we need the mapping.json and I tried to find sources to create a full mapping. But I propose to, one way or another, find all proper mappings, and if possible put the icons already in the plugin.

On https://nominatim.openstreetmap.org/ui/search.html I see also the icons, so there must be some logic to find all mappings...

I think I'm going to release current version (without the icons), unless you think it is fixable on very short term?

**Comment by rduivenvoorde** [comment]
@cxcandid ah duh, now I found: https://github.com/osm-search/nominatim-ui/blob/master/src/components/MapIcon.svelte

So apparently your json comes from that one, and it is not possible to match more icons :-(

Ok, the I propose to try to prefetch all these icons, put them in the icons folder so we have a cache and there is no need to fetch them again from the nominatim site for every result in every search

**Comment by rduivenvoorde** [comment]
@cxcandid can you please check out master now?

I've fixed the issue with the Qt warning: that was because on Linux the icon result names (Linestring.png) were not valid (because Linux has a case sensitive filesystem)...

AND I fetched al icons from mapicons.json and saved them in the icons dir, so we do not fetch them from nominatim.org anymore

If you test, I'll release :-)

**Comment by cxcandid** [comment]
@rduivenvoorde good idea to download all icons, as long as they are available ;-)

Tested on QGIS 3.28.13 and 3.34.1 (Windows). You can release, thank you! 🍾🥂 😊

**Comment by rduivenvoorde** [comment]
Ok: released!

**Pull request merged**
