### PR TITLE
QGIS Nominatim Locator Filter Extensions

### PR DESCRIPTION
**Pull request by cxcandid**
@rduivenvoorde  I'm a big fan of your Nominatim Locator Filter plugin and still use it even though it was directly built into QGIS.

Since I was missing a few features, I decided to extend the plugin.

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Thanks! Will merge and release, sorry for taking so much time.

**Comment by rduivenvoorde** [comment]
@cxcandid I do not see the icons? I also do not see an 'icon' item in the geojson results from:

https://nominatim.openstreetmap.org/search?polygon_geojson=1&format=json&polygon_threshold=0&limit=30&q=USA%20

image

Did OSM change output? Or do I miss files?

**Comment by cxcandid** [comment]
@rduivenvoorde thank you for taking the time to merge the code!

You are right that there have been changes in the OSM output... this must have happened in the last few weeks.
I'll try to adjust the code accordingly.

**Comment by cxcandid** [comment]
@rduivenvoorde Unfortunately, the icon URLs are no longer part of the OSM JSON and JSONV2 response 🙁.

**Comment by cxcandid** [comment]
We could use `class` and `type` attribute of JSON response to map the different icons.

**Pull request merged**
